# Generated by Django 4.2.25 on 2025-11-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_mensagemcontato_alter_funcionarios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.RenameField(
            model_name='mensagemcontato',
            old_name='mensagem',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
